apisix:
  image:
    repository: {{ .KubernetesOpts.APISIXImageRepo }}
    tag: {{ .KubernetesOpts.APISIXImageTag }}
  replicaCount: {{ .KubernetesOpts.ReplicaCount }}
  setIDFromPodUID: true
  luaModuleHook:
    enabled: true
    luaPath: "/lua-module-hook/?.ljbc"
    hookPoint: cloud
    configMapRef:
      name: "cloud-module"
      mounts:
        - key: cloud.ljbc
          path: /lua-module-hook/cloud.ljbc
        - key: cloud-agent.ljbc
          path: /lua-module-hook/cloud/agent.ljbc
        - key: cloud-metrics.ljbc
          path: /lua-module-hook/cloud/metrics.ljbc
        - key: cloud-utils.ljbc
          path: /lua-module-hook/cloud/utils.ljbc
  customLuaSharedDicts:
    - name: cloud
      size: 1m
gateway:
  tls:
    enabled: true
    existingCASecret: cloud-ssl
    certCAFilename: "ca.crt"
admin:
  enabled: false
etcd:
  enabled: false
  host:
    - "https://{{ .ControlPlane.Domain }}:443"
  timeout: 30
  auth:
    tls:
      enabled: true
      sni: {{ .ControlPlane.Domain }}
      existingSecret: cloud-ssl
      certFilename: tls.crt
      certKeyFilename: tls.key