
name: build the binary and push it to the release page
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go Environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.16.5'
      - name: Set tag
          run: |
            echo "BINARY_TAG=`git describe --tags --abbrev=0`" >> $GITHUB_ENV
      - name: Build Cloud-cli binary
        run: |
          make build
      - name: Push Cloud-cli binary
        env:
          REGISTRY: ${{ steps.login-ecr-staging.outputs.registry }}
          BINARY_TAG: ${{ env.BINARY_TAG }}
        run: |
          git tag api7/cloud-cli:dev $REGISTRY/cloud-cli:$BINARY_TAG
          git push $REGISTRY/cloud-cli:$BINARY_TAG
      - name: Push Cloud-cli binary (Production)
        env:
          REGISTRY: ${{ steps.login-ecr-prod.outputs.registry }}
          IMAGE_TAG: ${{ env.IMAGE_TAG }}
        run: |
          git tag api7/cloud-cli:dev $REGISTRY/cloud-cli:$BINARY_TAG
          git push $REGISTRY/cloud-cli:$BINARY_TAG

