name: Lint Checkers

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  changes:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      src: ${{ steps.filter.outputs.src }}
      docs: ${{ steps.filter.outputs.docs }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: |
            src:
              - '*.go'
              - '**/*.go'
              - 'go.mod'
              - 'go.sum'
              - 'Makefile'
  gofmt:
    needs: changes
    if: |
      (needs.changes.outputs.src == 'true')
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go Environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.19.4'
      - name: Run gofmt Check
        working-directory: ./
        run: |
          diffs=`gofmt -l .`
          if [[ -n $diffs ]]; then
              echo "Files are not formatted by gofmt:"
              echo $diffs
              exit 1
          fi
  golint:
    needs: changes
    if: |
      (needs.changes.outputs.src == 'true')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Setup Go Environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.19.4'
      - name: Download golangci-lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0
      - name: Run Golang Linters
        working-directory: ./
        run: |
          PATH=${PATH}:$(go env GOPATH)/bin make lint
  markdownlint:
    name: 🍇 Markdown
    needs: changes
    timeout-minutes: 5
    if: |
      (needs.changes.outputs.docs == 'true')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🚀 Use Node.js
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      - run: npm install -g markdownlint-cli@0.25.0
      - run: markdownlint '**/*.md' --ignore node_modules
