name: Build binaries and push them to the release page
on:
  push:
    tags:
      - '**'
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: Setup Go Environment
        uses: actions/setup-go@v1
        with:
          go-version: '1.17.10'
      - name: Build Cloud-cli binary
        run: |
          make build-all
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: "bin/**"
